title: Standaard
sections:
  main:
    display: Main
    fields:
      -
        handle: template
        field:
          type: hidden
          default: app
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        import: content
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
